#!/bin/bash

fileVar=$(find . -name "$1")

if [[ "$fileVar" != "" ]]; then
    echo -n "Файл уже существует. Перезаписать? (y/N) "

    read item
    case "$item" in
        y|Y) rm -f "$1" ;;
        *) echo "Файл не был перезаписан."
          exit 0 ;;
    esac
fi

touch $1
echo "Файл $1 создан пользователем $USER"

for (( i=1; i<=10; i++))
do
    echo "$i | $2" >> $1
done

echo "Файл $1 типа $(file "$1") заполнен 10-ю строками <$2>"
